package com.bmac.surwayapp.Model

data class PostApiModel(
    var SrNo: Int = 0,
    var MachineNo:String = "",
    var V_code:String = "",
    var G_code:String = "",
    var v_Name:String = "",
    var g_name:String = "",
    var f_name:String = "",
    var variety:String = "",
    var Ctype:String = "",
    var plotNo:String = "",
    var Wardno:String = "",
    //var Plot_Vcode:String = "",
    var Kitta: String = "",
    var East: String = "",
    var West: String = "",
    var North: String = "",
    var South: String = "",
    var Area:String = "",
    var sdate:String = "",
    var lat1:String = "",
    var lat2:String = "",
    var lat3:String = "",
    var lat4:String = "",
    var lat5:String = "",
    var lat6:String = "",
    var lat7:String = "",
    var lat8:String = "",
    var long1:String = "",
    var long2:String = "",
    var long3:String = "",
    var long4:String = "",
    var long5:String = "",
    var long6:String = "",
    var long7:String = "",
    var long8:String = "",
    var Dis1:Double = 0.00,
    var Dis2:Double = 0.00,
    var Dis3:Double = 0.00,
    var Dis4:Double = 0.00

)